`timescale 1ns/1ps
/*
    Scenario testbench: ikautil_sdram against the MiSTer 128MB module model.

    Enabled slots (110MHz config, 6-slot limit):
      slot0/1: ROM, chip0 mirror pair, DW=64   slot4/5: ROM, chip1 mirror pair, DW=64
      slot8:   R/W, chip0 bank2, DW=16         slot10:  R/W, chip1 bank2, DW=16

    Scenarios:
      S1 single reads          S2 row-hit chain      S3 4-slot concurrent burst
      S4 write/readback + padding-mask neighbor check
      S5 mirror-bank relatch   S6 refresh collision  S7 random soak w/ scoreboard

    ROM banks are preloaded with pat(chip, word_addr); mirror pairs hold
    identical data. The model's own timing checkers print "ERROR" on any
    violation - the run script fails on that.
*/
module tb;

localparam integer FREQ = 110;      //ucode bin (compile-time worst case)
//run the bus at a round 10ns period: legal for the <=110MHz ucode (all waits
//grow in ns) and keeps the model's real-valued $time checks free of ps rounding
localparam real    PERIOD = 10.0;

reg clk = 0;
always #(PERIOD / 2.0) clk = ~clk;

reg rst_n = 0;
reg rfsh  = 0;

//----------------------------------------------------------------------------
// DUT hookup
//----------------------------------------------------------------------------
wire [15:0] sd_dq;
wire [12:0] sd_a;
wire [1:0]  sd_ba;
wire        sd_ncs, sd_nras, sd_ncas, sd_nwe, sd_dqml, sd_dqmh, sd_cke;
wire        init_done;

reg  [11:0] rd_r = 0, wr_r = 0;
reg  [22:0] a_r  [0:11];
reg  [15:0] di_r [0:11];
wire [11:0] busy_w, rdy_w, dst_w;
wire [63:0] do0, do1, do4, do5;
wire [15:0] do8, do10;
wire [15:0] rdata_w;

reg         pl_en = 0, pl_wr = 0, pl_rd = 0;
reg  [25:0] pl_a = 0;
reg  [15:0] pl_di = 0;
wire        pl_busy;
wire [15:0] pl_do;

initial begin : init_arrays
    integer k;
    for (k = 0; k < 12; k = k + 1) begin a_r[k] = 23'd0; di_r[k] = 16'd0; end
end

ikautil_sdram #(
    .FREQ(FREQ), .DQM_SHARED(1), .CAP_DELAY(0), .INIT_PAUSE(100), .RFSHCNT(9)
) dut (
    .i_CLK(clk), .i_RST_n(rst_n), .i_RFSH(rfsh), .o_INIT_DONE(init_done),

    .i_PRELOAD(pl_en), .i_PRELOAD_A(pl_a), .i_PRELOAD_DI(pl_di),
    .i_PRELOAD_WR(pl_wr), .i_PRELOAD_RD(pl_rd),
    .o_PRELOAD_BUSY(pl_busy), .o_PRELOAD_DO(pl_do),

    .o_RDATA(rdata_w),
    .o_SLOT0_DST(dst_w[0]),  .o_SLOT1_DST(dst_w[1]),  .o_SLOT2_DST(dst_w[2]),   .o_SLOT3_DST(dst_w[3]),
    .o_SLOT4_DST(dst_w[4]),  .o_SLOT5_DST(dst_w[5]),  .o_SLOT6_DST(dst_w[6]),   .o_SLOT7_DST(dst_w[7]),
    .o_SLOT8_DST(dst_w[8]),  .o_SLOT9_DST(dst_w[9]),  .o_SLOT10_DST(dst_w[10]), .o_SLOT11_DST(dst_w[11]),

    .io_SDRAM_DQ(sd_dq), .o_SDRAM_A(sd_a), .o_SDRAM_BA(sd_ba),
    .o_SDRAM_nCS(sd_ncs), .o_SDRAM_nRAS(sd_nras), .o_SDRAM_nCAS(sd_ncas),
    .o_SDRAM_nWE(sd_nwe), .o_SDRAM_DQML(sd_dqml), .o_SDRAM_DQMH(sd_dqmh),
    .o_SDRAM_CKE(sd_cke),

    .o_SLOT0_BUSY(busy_w[0]),  .o_SLOT1_BUSY(busy_w[1]),  .o_SLOT2_BUSY(busy_w[2]),  .o_SLOT3_BUSY(busy_w[3]),
    .o_SLOT4_BUSY(busy_w[4]),  .o_SLOT5_BUSY(busy_w[5]),  .o_SLOT6_BUSY(busy_w[6]),  .o_SLOT7_BUSY(busy_w[7]),
    .o_SLOT0_RDY(rdy_w[0]),    .o_SLOT1_RDY(rdy_w[1]),    .o_SLOT2_RDY(rdy_w[2]),    .o_SLOT3_RDY(rdy_w[3]),
    .o_SLOT4_RDY(rdy_w[4]),    .o_SLOT5_RDY(rdy_w[5]),    .o_SLOT6_RDY(rdy_w[6]),    .o_SLOT7_RDY(rdy_w[7]),
    .i_SLOT0_RD(rd_r[0]),      .i_SLOT1_RD(rd_r[1]),      .i_SLOT2_RD(rd_r[2]),      .i_SLOT3_RD(rd_r[3]),
    .i_SLOT4_RD(rd_r[4]),      .i_SLOT5_RD(rd_r[5]),      .i_SLOT6_RD(rd_r[6]),      .i_SLOT7_RD(rd_r[7]),
    .i_SLOT0_A(a_r[0]), .i_SLOT1_A(a_r[1]), .i_SLOT2_A(a_r[2]), .i_SLOT3_A(a_r[3]),
    .i_SLOT4_A(a_r[4]), .i_SLOT5_A(a_r[5]), .i_SLOT6_A(a_r[6]), .i_SLOT7_A(a_r[7]),
    .o_SLOT0_DO(do0), .o_SLOT1_DO(do1), .o_SLOT2_DO(), .o_SLOT3_DO(),
    .o_SLOT4_DO(do4), .o_SLOT5_DO(do5), .o_SLOT6_DO(), .o_SLOT7_DO(),

    .o_SLOT8_BUSY(busy_w[8]), .o_SLOT9_BUSY(busy_w[9]), .o_SLOT10_BUSY(busy_w[10]), .o_SLOT11_BUSY(busy_w[11]),
    .o_SLOT8_RDY(rdy_w[8]),   .o_SLOT9_RDY(rdy_w[9]),   .o_SLOT10_RDY(rdy_w[10]),   .o_SLOT11_RDY(rdy_w[11]),
    .i_SLOT8_RD(rd_r[8]),     .i_SLOT9_RD(rd_r[9]),     .i_SLOT10_RD(rd_r[10]),     .i_SLOT11_RD(rd_r[11]),
    .i_SLOT8_WR(wr_r[8]),     .i_SLOT9_WR(wr_r[9]),     .i_SLOT10_WR(wr_r[10]),     .i_SLOT11_WR(wr_r[11]),
    .i_SLOT8_A(a_r[8]), .i_SLOT9_A(a_r[9]), .i_SLOT10_A(a_r[10]), .i_SLOT11_A(a_r[11]),
    .i_SLOT8_DI(di_r[8]), .i_SLOT9_DI(di_r[9]), .i_SLOT10_DI(di_r[10]), .i_SLOT11_DI(di_r[11]),
    .o_SLOT8_DO(do8), .o_SLOT9_DO(), .o_SLOT10_DO(do10), .o_SLOT11_DO()
);

mister_128mb u_mod (
    .clk(clk), .dq(sd_dq), .a(sd_a), .ba(sd_ba),
    .ncs(sd_ncs), .nras(sd_nras), .ncas(sd_ncas), .nwe(sd_nwe),
    .dqml(sd_dqml), .dqmh(sd_dqmh), .cke(sd_cke)
);

//----------------------------------------------------------------------------
// memory content: the chips load sdram_bank0..3.hex themselves (generated by
// run.sh). Both chips hold identical content; ROM mirror banks 0/1 identical.
// NOTE: no hierarchical references into the model arrays - verilator --timing
// makes the model's own array reads stale by one cycle when a TB scope writes
// them hierarchically.
//----------------------------------------------------------------------------
function automatic [15:0] pat(input [22:0] wa);
    pat = wa[15:0] ^ {wa[22:16], 9'h0};
endfunction

//RW banks carry a bank tag so ROM/RW mixups are caught
function automatic [15:0] patrw(input [1:0] bank, input [22:0] wa);
    patrw = pat(wa) ^ {14'd0, bank};
endfunction

//----------------------------------------------------------------------------
// helpers
//----------------------------------------------------------------------------
integer errors = 0;
integer cycle = 0;
always @(posedge clk) cycle = cycle + 1;

integer lat_sum = 0, lat_n = 0, lat_max = 0;

//per-slot request bookkeeping
integer t_req [0:11];

task automatic fire_read(input int s, input [22:0] addr);
    @(negedge clk);
    a_r[s] = addr; rd_r[s] = 1'b1; t_req[s] = cycle;
    @(negedge clk);
    rd_r[s] = 1'b0;
endtask

task automatic fire_write(input int s, input [22:0] addr, input [15:0] d);
    @(negedge clk);
    a_r[s] = addr; di_r[s] = d; wr_r[s] = 1'b1; t_req[s] = cycle;
    @(negedge clk);
    wr_r[s] = 1'b0;
endtask

task automatic preload_wr(input [25:0] a, input [15:0] d);
    int t0;
    @(negedge clk);
    pl_a = a; pl_di = d; pl_wr = 1'b1;
    @(negedge clk);
    pl_wr = 1'b0;
    t0 = cycle;
    while (pl_busy) begin
        @(posedge clk);
        if (cycle - t0 > 3000) begin $display("FATAL: preload wr timeout"); $finish; end
    end
endtask

task automatic preload_rd(input [25:0] a, output [15:0] d);
    int t0;
    @(negedge clk);
    pl_a = a; pl_rd = 1'b1;
    @(negedge clk);
    pl_rd = 1'b0;
    t0 = cycle;
    while (pl_busy) begin
        @(posedge clk);
        if (cycle - t0 > 3000) begin $display("FATAL: preload rd timeout"); $finish; end
    end
    d = pl_do;
endtask

task automatic wait_rdy(input int s, input int timeout = 3000);
    int t0;
    t0 = cycle;
    while (!rdy_w[s]) begin
        @(posedge clk);
        if (cycle - t0 > timeout) begin
            $display("FATAL: slot%0d RDY timeout", s);
            errors = errors + 1;
            $finish;
        end
    end
    lat_sum = lat_sum + (cycle - t_req[s]);
    lat_n   = lat_n + 1;
    if (cycle - t_req[s] > lat_max) lat_max = cycle - t_req[s];
    @(posedge clk);
endtask

function automatic [63:0] slot_do(input int s);
    case (s)
        0: slot_do = do0;   1: slot_do = do1;
        4: slot_do = do4;   5: slot_do = do5;
        8: slot_do = {48'd0, do8};
        10: slot_do = {48'd0, do10};
        default: slot_do = '0;
    endcase
endfunction

//expected 64-bit ROM read data (4-word aligned address)
function automatic [63:0] rom_exp(input [22:0] sa, input [22:0] addr);
    logic [22:0] wa;
    wa = sa + addr;
    rom_exp = {pat(wa+3), pat(wa+2), pat(wa+1), pat(wa)};
endfunction

task automatic check64(input string tag, input [63:0] got, input [63:0] exp);
    if (got !== exp) begin
        $display("ERROR: %s got=%h exp=%h (cycle %0d)", tag, got, exp, cycle);
        errors = errors + 1;
    end
endtask

task automatic check16(input string tag, input [15:0] got, input [15:0] exp);
    if (got !== exp) begin
        $display("ERROR: %s got=%h exp=%h (cycle %0d)", tag, got, exp, cycle);
        errors = errors + 1;
    end
endtask

//----------------------------------------------------------------------------
// scenarios
//----------------------------------------------------------------------------
localparam [22:0] SA0 = 23'h00_0000, SA1 = 23'h10_0000;   //match DUT defaults

//scoreboard for RW slots (bank2 of each chip)
reg [15:0] sh8  [int];
reg [15:0] sh10 [int];

integer i, j, t0;
integer lat1, lat2;
reg [63:0] d64;

initial begin
    repeat (4) @(negedge clk);
    rst_n = 1;

    //S0: init
    t0 = cycle;
    while (!init_done) begin
        @(posedge clk);
        if (cycle - t0 > 100000) begin $display("FATAL: init timeout"); $finish; end
    end
    $display("[S0] init done at cycle %0d", cycle);

    //S1: single reads, each slot, distinct rows
    for (i = 0; i < 4; i = i + 1) begin
        automatic int s = (i < 2) ? i : i + 2;              //slots 0,1,4,5
        fire_read(s, 23'(i) * 23'h1000 + 23'h40);           //4-aligned
        wait_rdy(s);
        check64($sformatf("S1 slot%0d", s),
                slot_do(s), rom_exp((s == 1 || s == 5) ? SA1 : SA0, 23'(i)*23'h1000 + 23'h40));
    end
    $display("[S1] single reads ok, avg latency so far %0d cycles", lat_sum / lat_n);

    //S2: row-hit chain on slot0 (same row, consecutive 4-word blocks)
    lat1 = lat_sum; lat2 = lat_n;
    for (i = 0; i < 8; i = i + 1) begin
        fire_read(0, 23'h2000 + 23'(i)*4);
        wait_rdy(0);
        check64("S2", slot_do(0), rom_exp(SA0, 23'h2000 + 23'(i)*4));
    end
    $display("[S2] row-hit chain ok, avg latency %0d cycles",
             (lat_sum - lat1) / (lat_n - lat2));

    //S3: concurrent reads on 4 ROM slots (both chips, both mirror banks)
    begin
        automatic int slots [4] = '{0, 1, 4, 5};
        @(negedge clk);
        for (i = 0; i < 4; i = i + 1) begin
            a_r[slots[i]] = 23'h3000 + 23'(i)*23'h800;
            rd_r[slots[i]] = 1'b1; t_req[slots[i]] = cycle;
        end
        @(negedge clk);
        for (i = 0; i < 4; i = i + 1) rd_r[slots[i]] = 1'b0;
        for (i = 0; i < 4; i = i + 1) wait_rdy(slots[i]);
        for (i = 0; i < 4; i = i + 1)
            check64($sformatf("S3 slot%0d", slots[i]), slot_do(slots[i]),
                    rom_exp((slots[i] == 1 || slots[i] == 5) ? SA1 : SA0,
                            23'h3000 + 23'(i)*23'h800));
        $display("[S3] concurrent 4-slot ok");
    end

    //S4: write/readback with padding-mask neighbor checks (DW16 on BL4 chip)
    fire_write(8, 23'h0100, 16'hBEEF); wait_rdy(8); sh8[23'h0100] = 16'hBEEF;
    fire_write(10, 23'h0204, 16'hCAFE); wait_rdy(10); sh10[23'h0204] = 16'hCAFE;
    fire_read(8, 23'h0100); wait_rdy(8);
    check16("S4 slot8 rb", do8, 16'hBEEF);
    fire_read(8, 23'h0101); wait_rdy(8);      //neighbor must be unclobbered
    check16("S4 slot8 nbr", do8, patrw(2'd2, 23'h0101));
    fire_read(8, 23'h0103); wait_rdy(8);
    check16("S4 slot8 nbr3", do8, patrw(2'd2, 23'h0103));
    fire_read(10, 23'h0204); wait_rdy(10);
    check16("S4 slot10 rb", do10, 16'hCAFE);
    fire_read(10, 23'h0205); wait_rdy(10);
    check16("S4 slot10 nbr", do10, patrw(2'd2, 23'h0205));
    $display("[S4] write/readback + padding mask ok");

    //S5: mirror relatch: 3 different rows on the slot0/1 pair
    lat1 = lat_sum; lat2 = lat_n;
    fire_read(0, 23'h0000); wait_rdy(0);   //row A -> bank0 or 1
    check64("S5 rowA", slot_do(0), rom_exp(SA0, 23'h0000));
    fire_read(0, 23'h8000); wait_rdy(0);   //row B -> mirror bank, no precharge
    check64("S5 rowB", slot_do(0), rom_exp(SA0, 23'h8000));
    fire_read(0, 23'h10000); wait_rdy(0);  //row C -> relatch (PRE + ACT)
    check64("S5 rowC", slot_do(0), rom_exp(SA0, 23'h10000));
    $display("[S5] mirror/relatch ok");

    //S6: refresh burst colliding with reads
    @(negedge clk); rfsh = 1'b1;
    fire_read(0, 23'h4000);
    fire_read(4, 23'h5000);
    @(negedge clk); rfsh = 1'b0;
    wait_rdy(0); wait_rdy(4);
    check64("S6 slot0", slot_do(0), rom_exp(SA0, 23'h4000));
    check64("S6 slot4", slot_do(4), rom_exp(SA0, 23'h5000));
    repeat (300) @(posedge clk);   //let the refresh debt drain
    $display("[S6] refresh collision ok");

    //S7: random soak with scoreboard
    for (i = 0; i < 400; i = i + 1) begin
        automatic int pick = $urandom_range(0, 5);
        automatic int s = (pick < 2) ? pick : (pick < 4) ? pick + 2 : (pick == 4) ? 8 : 10;
        automatic logic chip = (s == 4 || s == 5 || s == 10);
        if (s < 8) begin
            automatic logic [22:0] ad = {$urandom_range(0, 255) [7:0], $urandom_range(0, 255) [7:0]} & 23'h00_FFFC;
            fire_read(s, ad); wait_rdy(s);
            check64($sformatf("S7.%0d slot%0d", i, s), slot_do(s),
                    rom_exp((s == 1 || s == 5) ? SA1 : SA0, ad));
        end
        else begin
            automatic logic [22:0] ad = 23'($urandom_range(0, 16383));
            if ($urandom_range(0, 1)) begin
                automatic logic [15:0] d = 16'($urandom());
                fire_write(s, ad, d); wait_rdy(s);
                if (s == 8) sh8[ad] = d; else sh10[ad] = d;
            end
            else begin
                automatic logic [15:0] exp;
                fire_read(s, ad); wait_rdy(s);
                if (s == 8) exp = sh8.exists(int'(ad)) ? sh8[int'(ad)] : patrw(2'd2, ad);
                else        exp = sh10.exists(int'(ad)) ? sh10[int'(ad)] : patrw(2'd2, ad);
                check16($sformatf("S7.%0d slot%0d", i, s), (s == 8) ? do8 : do10, exp);
            end
        end
        //sprinkle refresh
        if (i % 100 == 50) begin
            @(negedge clk); rfsh = 1'b1; @(negedge clk); rfsh = 1'b0;
        end
    end
    $display("[S7] random soak ok");

    //S8: jtframe-style early path - beats on o_RDATA from the DST strobe,
    //and first-word latency measurement
    begin
        automatic int t_fire, t_dst;
        automatic logic [63:0] early;
        fire_read(0, 23'h6100);
        t_fire = t_req[0];
        while (!dst_w[0]) @(posedge clk);
        t_dst = cycle;
        early[15:0] = rdata_w;
        for (i = 1; i < 4; i = i + 1) begin
            @(posedge clk);
            early[i*16 +: 16] = rdata_w;
        end
        wait_rdy(0);
        check64("S8 early beats", early, rom_exp(SA0, 23'h6100));
        check64("S8 vs DO", early, slot_do(0));
        $display("[S8] DST early path ok, first word at %0d cycles (%.0f ns), full RDY at %0d cycles",
                 t_dst - t_fire, real'(t_dst - t_fire) * PERIOD, cycle - 1 - t_fire);
    end

    //S9: whole-SDRAM preload port - write/verify across chips and banks,
    //mirror duplication by the loader, then read through a slot
    begin
        automatic logic [25:0] base;
        automatic logic [15:0] d;
        pl_en = 1'b1;
        //write 8 words into every bank of both chips at row 0x555
        for (i = 0; i < 8; i = i + 1) begin          //{chip,ba} = 0..7
            for (j = 0; j < 8; j = j + 1) begin
                base = {i[2:0], 13'h0555, 10'(j)};
                preload_wr(base, 16'hD000 ^ 16'(i*256 + j));
            end
            if (i == 3) begin                        //refresh must coexist
                @(negedge clk); rfsh = 1'b1; @(negedge clk); rfsh = 1'b0;
            end
        end
        //verify every word through i_PRELOAD_RD
        for (i = 0; i < 8; i = i + 1) begin
            for (j = 0; j < 8; j = j + 1) begin
                base = {i[2:0], 13'h0555, 10'(j)};
                preload_rd(base, d);
                check16($sformatf("S9 verify c%0db%0d w%0d", i[2], i[1:0], j),
                        d, 16'hD000 ^ 16'(i*256 + j));
            end
        end
        pl_en = 1'b0;
        //banks 0 and 1 of chip0 got identical row-0x555 content (i=0 vs i=1
        //differ though) -> read through slot0 hits whichever mirror bank opens;
        //write both banks with the SAME data first to make it slot-readable
        pl_en = 1'b1;
        for (j = 0; j < 4; j = j + 1) begin
            preload_wr({3'd0, 13'h0556, 10'(j)}, 16'hE500 ^ 16'(j));
            preload_wr({3'd1, 13'h0556, 10'(j)}, 16'hE500 ^ 16'(j));   //mirror copy
        end
        pl_en = 1'b0;
        fire_read(0, {13'h0556, 10'd0}); wait_rdy(0);
        check64("S9 slot read of preloaded", slot_do(0),
                {16'hE500 ^ 16'd3, 16'hE500 ^ 16'd2, 16'hE500 ^ 16'd1, 16'hE500 ^ 16'd0});
        $display("[S9] preload write/verify/mirror ok");
    end

    $display("latency: n=%0d avg=%0d max=%0d cycles (%.1f / %.1f ns at %0dMHz)",
             lat_n, lat_sum / lat_n, lat_max,
             real'(lat_sum) / real'(lat_n) * PERIOD, real'(lat_max) * PERIOD, FREQ);
    if (errors == 0) $display("ALL SCENARIOS PASSED");
    else             $display("FAILED with %0d error(s)", errors);
    $finish;
end

//global watchdog
initial begin
    #6_000_000;   //6ms
    $display("FATAL: global watchdog");
    $finish;
end

//cycle-level trace for debugging (negedge: post-NBA, mid-cycle stable values)
`ifdef TRACE
always @(negedge clk) begin
    if (cycle >= `TRACE_FROM && cycle <= `TRACE_TO) begin
        $display("C%0d pins{ras%b cas%b we%b cs%b ba%b a%h} dq=%h oe%b rr=%h | u0{b%b t%0d rw%b c%0d s%0d bk%0d w=%h} u1{b%b t%0d rw%b c%0d s%0d bk%0d w=%h} | gr{v%b cl%0d s%0d bk%0d} pend=%b rdy=%b",
            cycle, sd_nras, sd_ncas, sd_nwe, sd_ncs, sd_ba, sd_a, sd_dq, dut.dq_oe, dut.rdata_reg,
            dut.u_busy[0], dut.u_type[0], dut.u_rw[0], dut.u_ctr[0], dut.u_slot[0], dut.u_bank[0], dut.u_word[0],
            dut.u_busy[1], dut.u_type[1], dut.u_rw[1], dut.u_ctr[1], dut.u_slot[1], dut.u_bank[1], dut.u_word[1],
            dut.gr_valid, dut.gr_class, dut.gr_slot, dut.gr_bank, busy_w, rdy_w);
        $display("   chip0{doe%b die%b bank%0d col%h brst%h bcnt%h en%b} dqm=%b r1=%b r0=%b dqdqm=%h",
            u_mod.chip0.Data_out_enable, u_mod.chip0.Data_in_enable,
            u_mod.chip0.Bank, u_mod.chip0.Col, u_mod.chip0.Col_brst,
            u_mod.chip0.Burst_counter, u_mod.chip0.Dq_en,
            u_mod.chip0.Dqm, u_mod.chip0.Dqm_reg1, u_mod.chip0.Dqm_reg0, u_mod.chip0.Dq_dqm);
    end
end
`endif

endmodule
